export const environment = {
	production: true,
	authUrl: 'http://localhost:8080/api/auth',
	loginUrl: 'http://localhost:8080/api/loginextended',
	registerUrl: 'http://localhost:8080/api/registerextended',
	userInfoUrl: 'http://localhost:8080/api/UserProfile',
	userCheckerUrl: 'http://localhost:8080/api/user',
	cocktailGetUrl: 'http://localhost:8080/api/cocktail',
	logoutUrl: 'http://localhost:8080/api/logout',
	refreshUrl: 'http://localhost:8080/api/refreshextended',
	searchUrl: 'http://localhost:8080/api/search',
	settingsUrl: 'http://localhost:8080/api/preferences',
	glassUrl: 'http://localhost:8080/api/glassesTable',
	ingredientUrl: 'http://localhost:8080/api/ingredientsTable',
	favoriteUrl: 'http://localhost:8080/api/favorites',
	isFavoriteUrl: 'http://localhost:8080/api/isInFavorites',
	userProfileUrl: 'http://localhost:8080/api/userProfile',
	categoriesUrl: 'http://localhost:8080/api/categoriesTable',
	suggestedDrinksUrl: 'http://localhost:8080/api/suggestedDrinks',
	allCocktailsUrl: 'http://localhost:8080/api/allCocktails',
};
