export const environment = {
	production: true,
	authUrl: 'localhost:8000',
	loginUrl: 'localhost:8000/login',
	registerUrl: 'localhost:8000/register',
	userInfoUrl: 'localhost:8000/UserProfile',
	userCheckerUrl: 'localhost:8000/user',
	cocktailGetUrl: '/cocktail',
	logoutUrl: 'localhost:8000/logout',
	refreshUrl: 'localhost:8000/api/refreshextended',
	searchUrl: 'localhost:8000/search',
	settingsUrl: 'localhost:8000/preferences',
	glassUrl: 'localhost:8000/glass',
	favoriteUrl: 'localhost:8000/favorites',
	ingredientUrl: 'localhost:8000/ingredientsTable',
	isFavoriteUrl: 'localhost:8000/isInFavorites',
	userProfileUrl: 'localhost:8000/userProfile',
	categoriesUrl: 'localhost:8000/categoriesTable',
	suggestedDrinksUrl: 'localhost:8000/suggestedDrinks',
	allCocktailsUrl: 'localhost:8000/allCocktails',
	editCocktailUrl: 'localhost:8000/editCocktails',
};
