export const environment = {
	production: true,
	authUrl: 'https://localhost:8081/api/auth',
	loginUrl: 'https://localhost:8081/api/loginextended',
	registerUrl: 'https://localhost:8081/api/registerextended',
	userInfoUrl: 'https://localhost:8081/api/UserProfile',
	userCheckerUrl: 'https://localhost:8081/api/user',
	cocktailGetUrl: 'https://localhost:8081/api/cocktail',
	logoutUrl: 'https://localhost:8081/api/logout',
	refreshUrl: 'https://localhost:8081/api/refreshextended',
	searchUrl: 'https://localhost:8081/api/search',
	settingsUrl: 'https://localhost:8081/api/preferences',
	glassUrl: 'https://localhost:8081/api/glassesTable',
	ingredientUrl: 'https://localhost:8081/api/ingredientsTable',
	favoriteUrl: 'https://localhost:8081/api/favorites',
	isFavoriteUrl: 'https://localhost:8081/api/isInFavorites',
	userProfileUrl: 'https://localhost:8081/api/userProfile',
	categoriesUrl: 'https://localhost:8081/api/categoriesTable',
	suggestedDrinksUrl: 'https://localhost:8081/api/suggestedDrinks',
	allCocktailsUrl: 'https://localhost:8081/api/allCocktails',
	editCocktailUrl: 'https://localhost:8081/api/editCocktails',
};
