export const environment = {
	production: false,
	authUrl: '/api/auth',
	loginUrl: '/api/loginextended',
	registerUrl: '/api/registerextended',
	userInfoUrl: '/api/UserProfile',
	userCheckerUrl: '/api/user',
	cocktailGetUrl: '/api/cocktail',
	logoutUrl: '/api/logout',
	refreshUrl: '/api/refreshextended',
	searchUrl: '/api/search',
	settingsUrl: '/api/preferences',
	glassUrl: '/api/glassesTable',
	ingredientUrl: '/api/ingredientsTable',
	favoriteUrl: '/api/favorites',
	isFavoriteUrl: '/api/isInFavorites',
	userProfileUrl: '/api/userProfile',
	categoriesUrl: '/api/categoriesTable',
	suggestedDrinksUrl: '/api/suggestedDrinks',
	allCocktailsUrl: '/api/allCocktails',
	editCocktailUrl: '/api/editCocktails',
	cocktailImgUploadUrl: '/api/uploadCocktailImage',
	userImgUploadUrl: '/api/uploadProfileImage',
};
